[build]
builder = "nixpacks"

[deploy]
startCommand = "mkdir -p .next/standalone/.next && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public && node .next/standalone/server.js"
restartPolicyType = "on_failure"
